version: '3.5'

services:
  api:
    image: nginx:latest
    container_name: task-api
    ports:
      - "8000:80"
    restart: always
    volumes:
      - ./docker/nginx/server.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    depends_on:
      - php
    networks:
      - php

  php:
    build:
      context: ./docker
    working_dir: /var/www
    container_name: task-api-php
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - db
      - php

  db:
    container_name: task-api-db
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticket_manager
      MYSQL_USER: ticket
      MYSQL_PASSWORD: t1ck3t
    networks:
      - db

  db_test:
    container_name: task-api-db_test
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticket_manager_test
      MYSQL_USER: ticket
      MYSQL_PASSWORD: t1ck3t
    networks:
      - db

networks:
  db:
  php:
